name: makola-online-staging
services:
- name: web-staging
  source_dir: /
  github:
    repo: your-username/makola-online
    branch: staging
  run_command: npm run preview
  build_command: npm ci && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: staging
  - key: ADMIN_SUPER_EMAIL
    value: dukesnr@yahoo.co.uk
  - key: ADMIN_WHATSAPP_NUMBER
    value: "0558271127"
  - key: APP_BASE_URL
    value: https://staging.makolaonline.com
  - key: VITE_ADMIN_PASSWORD
    value: Makola2025!
  - key: PLATFORM_COMMISSION_PERCENT
    value: "5"
  - key: MINIMUM_PAYOUT_AMOUNT
    value: "10"
  - key: MTN_MOMO_API_KEY
    value: test_mtn_key
  - key: VODAFONE_MOMO_API_KEY
    value: test_vodafone_key
  - key: AIRTELTIGO_MOMO_API_KEY
    value: test_airteltigo_key

domains:
- domain: staging.makolaonline.com
  type: PRIMARY

static_sites:
- name: frontend-staging
  source_dir: /
  build_command: npm ci && npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  routes:
  - path: /